### ISSUE TITLE
how does cross validation interact with transforms?

### ISSUE THREAD

**Issue by normrubin** [muellerzr/fastai-Experiments-and-tips#2]
I  must be missing something basic here.

then you get the parameters for the transformations like the mean and sd for normalization
and split the data into two parts - train_df and test_df

train_df and test_df are not normalized.  But the mean and sd are saved  for normalization 

in each iteration of the loop you compute 
     data_fold (different splitting, do the normalization based on the original mean and sd
      data_test use all  the data in test_df and the original normalization mean and sd 

 I would have thought the data_test is the same every iteration - so why is recomputed?

**Comment by muellerzr** [comment]
Because initially we need one DataLoader generated already to get the proper processing. You could make a dummy dataloader or modify the loop to only do this on the first runthrough this way you keep the test dataloader the same (Also this is much easier to do in v2, but the same idea to why is still the same)

**Comment by normrubin** [comment]
Thanks
